server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
logging.charset.console=UTF-8
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [requestId=%X{requestId}] %logger{36} - %msg%n
