DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS creators;

CREATE TABLE creators (
    creator_id BIGINT PRIMARY KEY,
    join_date DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE posts (
    post_id BIGINT PRIMARY KEY,
    creator_id BIGINT NOT NULL,
    post_date DATE NOT NULL,
    is_valid BOOLEAN NOT NULL,
    CONSTRAINT fk_posts_creator
        FOREIGN KEY (creator_id) REFERENCES creators(creator_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO creators (creator_id, join_date) VALUES
    (1, DATE_SUB(CURRENT_DATE, INTERVAL 100 DAY)),
    (2, DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY)),
    (3, DATE_SUB(CURRENT_DATE, INTERVAL 10 DAY)),
    (4, DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY));

INSERT INTO posts (post_id, creator_id, post_date, is_valid) VALUES
    (101, 1, CURRENT_DATE, TRUE),
    (102, 1, DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY), TRUE),
    (103, 1, DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY), FALSE),
    (104, 1, DATE_SUB(CURRENT_DATE, INTERVAL 4 DAY), TRUE),
    (105, 1, DATE_SUB(CURRENT_DATE, INTERVAL 7 DAY), TRUE),
    (106, 2, DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY), FALSE),
    (107, 2, DATE_SUB(CURRENT_DATE, INTERVAL 8 DAY), TRUE),
    (108, 2, DATE_SUB(CURRENT_DATE, INTERVAL 20 DAY), TRUE),
    (109, 3, DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY), TRUE),
    (110, 3, DATE_SUB(CURRENT_DATE, INTERVAL 2 DAY), TRUE),
    (111, 3, DATE_SUB(CURRENT_DATE, INTERVAL 3 DAY), TRUE),
    (112, 3, DATE_SUB(CURRENT_DATE, INTERVAL 4 DAY), TRUE),
    (113, 3, DATE_SUB(CURRENT_DATE, INTERVAL 5 DAY), TRUE);